elasticsearch:
  host: localhost
  port: 9200
  username: elastic
  password: elastic
  index_name: face_recognition

models:
  detector: weights/scrfd/scrfd_10g_bnkps.onnx
  extractor: weights/arcface/Glint100.onnx

recognition:
  similarity_threshold: 0.55
  top_k: 5

performance:
  batch_size: 32
  use_gpu: true